export const CREATE_DISH_REQUEST = 'CREATE_DISH_REQUEST';
export const CREATE_DISH_SUCCESS = 'CREATE_DISH_SUCCESS';
export const CREATE_DISH_FAILURE = 'CREATE_DISH_FAILURE';
export const GET_DISHES_REQUEST = 'GET_DISHES_REQUEST';
export const GET_DISHES_SUCCESS = 'GET_DISHES_SUCCESS';
export const GET_DISHES_FAILURE = 'GET_DISHES_FAILURE';
